// src/utils/quotes.ts

const quotes: string[] = [
    "Live less out of habit and more out of intent.",
    "Mindfulness isn't difficult, we just need to remember to do it.",
    "Every moment is a fresh beginning.",
    "Be where your feet are.",
    "Small intentional actions lead to big meaningful changes.",
    "Presence is the antidote to overwhelm.",
    "Intentional living is the art of making our own choices before others' choices make us.",
    "Do less. Be more.",
    "Clarity comes from stillness, not from speed.",
    "Your attention is your most valuable currency. Spend it wisely.",
    "Pause. Breathe. Proceed with purpose.",
    "Your direction is more important than your speed.",
    "Make space for what matters.",
    "Simplicity is the ultimate sophistication.",
    "Live deliberately.",
    "Less noise. More intention.",
    "Be mindful even if your mind is full.",
    "Let your values guide your schedule.",
    "Slow down to move forward.",
    "Choose your thoughts like you choose your clothes.",
    "Don’t just survive the day—shape it.",
    "Stillness speaks louder than chaos.",
    "Create a life that feels good on the inside, not just looks good on the outside.",
    "You become what you pay attention to.",
    "Intention sets the tone.",
    "Alignment over achievement.",
    "Decide what kind of life you actually want, then say no to everything that isn't that.",
    "Not everything requires your energy.",
    "Presence is a gift, not a given.",
    "Less scrolling. More being.",
    "Purpose doesn’t arrive. It’s practiced.",
    "Anchor yourself in what matters.",
    "Intentional choices make accidental joy.",
    "You don’t have to do everything. Just the right things.",
    "Time spent mindfully is time multiplied.",
    "The quality of your life is shaped by the quality of your attention.",
    "Quiet the noise to hear your truth.",
    "Give your energy to what gives you energy.",
    "Saying no is a way of saying yes to yourself.",
    "Wake up with purpose. Rest with peace.",
    "Let your days reflect your priorities.",
    "Live by design, not by default.",
    "Awareness is the first step to change.",
    "Create with intention. Consume with discernment.",
    "What you water grows.",
    "Inner peace begins the moment you choose not to allow another person or event to control your emotions.",
    "In a world of doing, pause for a moment of being.",
    "Purpose is found in presence.",
    "Don't trade your authenticity for approval.",
    "Focus is a form of self-respect.",
    "Simplify until it feels like peace.",
    "Mindful living is meaningful living.",
    "You can't do it all, and that's okay.",
    "Listen deeply. Respond intentionally.",
    "Curate your life like a gallery, not a storage unit.",
    "Be intentional with your yes and graceful with your no.",
    "Hustle less. Align more.",
    "Energy flows where attention goes.",
    "Your peace is precious. Guard it.",
    "Don't confuse movement with progress.",
    "A mindful life is a meaningful life.",
    "Intentions are the seeds of growth.",
    "Rest is not a reward. It's essential.",
    "Live in alignment, not in reaction.",
    "Presence is power.",
    "The way you live your days is the way you live your life.",
    "Show up for the life you actually want.",
    "Protect your peace like it's your greatest asset—because it is.",
    "Be the calm in your own storm.",
    "Let your life be a reflection of your values.",
    "Create space between stimulus and response.",
    "Intentional mornings create meaningful days.",
    "Do what feels right, not what looks right.",
    "Discipline is remembering what you want.",
    "A slower pace makes room for deeper connection.",
    "Be conscious of the life you're creating.",
    "Direction over distraction.",
    "You can’t control the waves, but you can learn to surf.",
    "Consciously choose what you consume—information, food, thoughts, and energy.",
    "Let stillness be your compass.",
    "Peace is a practice, not a place.",
    "Let go of what clutters your mind.",
    "The simplest things bring the most peace.",
    "Make room for what matters most.",
    "Awareness changes everything.",
    "You don’t need more time. You need more presence.",
    "Do what adds value, not noise.",
    "Intentional living is radical self-respect.",
    "Turn off autopilot.",
    "Breathe in clarity. Breathe out distraction.",
    "Don’t be busy. Be present.",
    "What you focus on expands.",
    "Mindful intention is the heartbeat of a meaningful life.",
    "Less hustle. More heart.",
    "Choose peace over perfection.",
    "When you align your actions with your values, life feels lighter.",
    "Stillness is where creativity lives.",
    "Live in tune with your inner compass.",
    "Be deliberate with your time.",
    "Keep only what inspires clarity and calm.",
    "Let your intention be your anchor in the chaos.",
    "Decide to be present before the world decides for you.",
    "Stay true to your inner rhythm.",
    "A meaningful life is a series of mindful choices.",
    "Lead with intention, follow with grace."
  ];
  
  export default quotes;
  